language: cpp
sudo: true
compiler:
 - gcc

dist: focal
os:
  - linux


cache:
  directories:
  - $HOME/cache
  - $HOME/OpenFOAM

stages:
  - build
  - run

addons:
  apt:
    update: true
    packages:
      - flexc++
      - libfl-dev
      - lcov
      - libopenmpi-dev

script: skip

_build: &_build
  stage: build
  before_install:
    - sudo sh -c "wget --no-check-certificate -O - https://dl.openfoam.org/gpg.key | apt-key add -"
    - sudo add-apt-repository http://dl.openfoam.org/ubuntu
    - sudo apt update
    - sudo apt-get -y install openfoam$VERSION
    - source /opt/openfoam$VERSION/etc/bashrc

  install:
    - ./scripts/travis_install_external_ginkgo.sh

  before_script:
    - cmake --version
    - mkdir build
    - cd build
    - cmake -DOGL_USE_EXTERNAL_GINKGO=$EXTERNAL_GINKGO ..

  script:
    - make -j4 && make install

_run: &_run
  stage: run
  before_install:
    - sudo sh -c "wget --no-check-certificate -O - https://dl.openfoam.org/gpg.key | apt-key add -"
    - sudo add-apt-repository http://dl.openfoam.org/ubuntu
    - sudo apt update
    - sudo apt-get -y install openfoam$VERSION
    - source /opt/openfoam$VERSION/etc/bashrc

  install:
    - git clone https://github.com/greole/OBR.git \
        $HOME/cache/OBR

  script:
      - ls /opt
      - ls $FOAM_SRC
      - ls $FOAM_USER_LIBBIN


jobs:
  include:
    - <<: *_build
      ENV:
      - VERSION=8
      - EXTERNAL_GINKGO=OFF
      - GINKGO_VERSION=develop
    - <<: *_build
      ENV:
      - VERSION=8
      - EXTERNAL_GINKGO=ON
      - GINKGO_VERSION=develop
    - <<: *_build
      ENV:
      - VERSION=8
      - EXTERNAL_GINKGO=ON
      - GINKGO_VERSION=331277a81b848f33705f6ccf4f910fff69c84e18
    - <<: *_build
      ENV:
      - VERSION=7
      - EXTERNAL_GINKGO=OFF
      - GINKGO_VERSION=develop
    - <<: *_build
      ENV:
      - VERSION=7
      - EXTERNAL_GINKGO=ON
      - GINKGO_VERSION=develop
    - <<: *_run
      ENV:
      - VERSION=8

