language: cpp
sudo: true
compiler:
 - gcc

dist: focal
os:
  - linux

env:
    - VERSION=8 EXTERNAL_GINKGO=OFF
    - VERSION=8 EXTERNAL_GINKGO=ON
    - VERSION=7 EXTERNAL_GINKGO=OFF
    - VERSION=7 EXTERNAL_GINKGO=ON

cache:
  directories:
  - $HOME/OpenFOAM


addons:
  apt:
    update: true
    packages:
      - flexc++
      - libfl-dev
      - lcov
      - libopenmpi-dev

before_install:
  - sudo sh -c "wget --no-check-certificate -O - https://dl.openfoam.org/gpg.key | apt-key add -"
  - sudo add-apt-repository http://dl.openfoam.org/ubuntu
  - sudo apt update

install:
  - sudo apt-get -y install openfoam$VERSION
  - source /opt/openfoam$VERSION/etc/bashrc


clone_external_ginkgo:
  - if: env(EXTERNAL_GINKGO) = ON
    - git clone https://github.com/ginkgo-project/ginkgo.git
    - cd ginkgo
    - mkdir build
    - cmake .. 
    - make 

before_script:
    
  - cmake --version -DOGL_USE_EXTERNAL_GINKGO=$EXTERNAL_GINKGO
  - mkdir build
  - cd build
  - cmake ..

script:
  - make -j4
