language: cpp
sudo: true
compiler:
 - gcc

dist: focal
os:
  - linux


cache:
  directories:
  - $HOME/cache

stages:
  - build
  - run

addons:
  apt:
    update: true
    packages:
      - flexc++
      - libfl-dev
      - lcov
      - libopenmpi-dev
      - ipython3

script: skip

_build: &_build
  stage: build
  if:
    branch = dev OR env(EXTERNAL_GINKGO) = OFF
  before_install:
    - sudo sh -c "wget --no-check-certificate -O - https://dl.openfoam.org/gpg.key | apt-key add -"
    - sudo add-apt-repository http://dl.openfoam.org/ubuntu
    - sudo apt update
    - sudo apt-get -y install openfoam$VERSION
    - source /opt/openfoam$VERSION/etc/bashrc
    - mkdir -p $HOME/data

  install:
    - ./scripts/travis_install_external_ginkgo.sh

  before_script:
    - cmake --version
    - mkdir build
    - cd build
    - cmake -DOGL_USE_EXTERNAL_GINKGO=$EXTERNAL_GINKGO ..

  script:
    - make -j4 && make install


_run: &_run
  stage: run
  before_install:
    - git clone -b develop https://github.com/greole/owls.git $HOME/owls
    - cd $HOME/owls
    - python setup.py install --user
    - source /opt/openfoam$VERSION/etc/bashrc

  install:
    - git clone https://github.com/greole/OBR.git $HOME/OBR
    - git clone https://develop.openfoam.com/committees/hpc.git $HOME/HPC
    - pip install docopt --user


  script:
      - ls /opt
      - ls $FOAM_SRC
      - ls $FOAM_USER_LIBBIN
      - cd $HOME/OBR
      - cat $HOME/OBR/airFoil2D.json
      - cat $HOME/OBR/lidDrivenCavity3D.json
      - python runBenchmark.py --solver $SOLVER --backend OF,GKO --executor Ref --preconditioner $PRECOND --field p --test-run  --fail_on_error  --report=report_airFoil.csv --folder=Test_airFoil --parameters=/home/travis/OBR/airFoil2D.json
      - python runBenchmark.py --solver $SOLVER --backend OF,GKO --executor Ref --preconditioner $PRECOND --field p --test-run  --fail_on_error  --report=report_lidDrivenCavity.csv --folder=Test_lidDrivenCavity --parameters=/home/travis/OBR/lidDrivenCavity3D.json
      - mkdir -p $HOME/data
      - cp report_*.csv $HOME/data/
      - cat $HOME/data/report_*.csv

_validate: &_validate
  stage: validate
  script:
      - echo $TRAVIS_BUILD_DIR
      - python $TRAVIS_BUILD_DIR/scripts/travis_check_results.py $HOME/data/report_airFoil.csv
      - python $TRAVIS_BUILD_DIR/scripts/travis_check_results.py $HOME/data/report_lidDrivenCavity.csv

jobs:
  Include:
    - <<: *_build
      ENV:
      - VERSION=8
      - EXTERNAL_GINKGO=OFF
      - GINKGO_VERSION=develop
      workspaces:
        create:
          name:
            foam_env_8
          paths:
            - /home/travis/OpenFOAM/travis-8
            - /opt/openfoam8
    - <<: *_build
      ENV:
      - VERSION=8
      - EXTERNAL_GINKGO=ON
      - GINKGO_VERSION=develop
    - <<: *_build
      ENV:
      - VERSION=8
      - EXTERNAL_GINKGO=ON
      - GINKGO_VERSION=331277a81b848f33705f6ccf4f910fff69c84e18
    - <<: *_build
      ENV:
      - VERSION=7
      - EXTERNAL_GINKGO=OFF
      - GINKGO_VERSION=develop
      workspaces:
        create:
          name:
            foam_user_libbin_7
          paths:
            /home/travis/OpenFOAM/travis-7
    - <<: *_build
      ENV:
      - VERSION=7
      - EXTERNAL_GINKGO=ON
      - GINKGO_VERSION=develop
    - <<: *_run
      ENV:
      - VERSION=8
      - SOLVER=CG
      - PRECOND=NoPrecond
      workspaces:
        use:
          - foam_env_8
        create:
          name:
            CGData
          paths:
            /home/travis/data
    - <<: *_run
      ENV:
      - VERSION=8
      - SOLVER=BiCGStab
      - PRECOND=NoPrecond
      workspaces:
        use:
          - foam_env_8
        create:
          name:
            BiCGStabData
          paths:
            /home/travis/data
    - <<: *_run
      ENV:
      - VERSION=8
      - SOLVER=CG
      - PRECOND=BJ
      workspaces:
        use:
          - foam_env_8
    - <<: *_run
      ENV:
      - VERSION=8
      - SOLVER=BiCGStab
      - PRECOND=BJ
      workspaces:
        use:
          - foam_env_8
    - <<: *_run
      ENV:
      - VERSION=8
      - SOLVER=IR
      - PRECOND=NoPrecond
      workspaces:
        use:
          - foam_env_8
    - <<: *_validate
      ENV:
      - SOLVER=CG
      - PRECOND=NoPrecond
      workspaces:
        use:
          - foam_env_8
          - CGData
    - <<: *_validate
      ENV:
      - SOLVER=BiCGStab
      - PRECOND=NoPrecond
      workspaces:
        use:
          - foam_env_8
          - BiCGStabData
