language: cpp
sudo: true
compiler:
 - gcc

dist: focal
os:
  - linux


env:
    - VERSION=8 EXTERNAL_GINKGO=OFF
    - VERSION=8 EXTERNAL_GINKGO=ON
    - VERSION=7 EXTERNAL_GINKGO=OFF
    - VERSION=7 EXTERNAL_GINKGO=ON

cache:
  directories:
  - $HOME/OpenFOAM

stages:
  - build
  - test

addons:
  apt:
    update: true
    packages:
      - flexc++
      - libfl-dev
      - lcov
      - libopenmpi-dev


jobs:
  include:
    - stage: build
        before_install:
          - sudo sh -c "wget --no-check-certificate -O - https://dl.openfoam.org/gpg.key | apt-key add -"
          - sudo add-apt-repository http://dl.openfoam.org/ubuntu
          - sudo apt update

        install:
          - sudo apt-get -y install openfoam$VERSION
          - source /opt/openfoam$VERSION/etc/bashrc
          - ./scripts/travis_install_external_ginkgo.sh

        before_script:
          - cmake --version
          - mkdir build
          - cd build
          - cmake -DOGL_USE_EXTERNAL_GINKGO=$EXTERNAL_GINKGO ..

        script:
          - make -j4

    - stage: test
      script:
        echo foo

