language: cpp
sudo: true
compiler:
 - gcc

dist: focal
os:
  - linux


cache:
  directories:
  - $HOME/cache
  - $HOME/OpenFOAM
  - /opt/openfoam7
  - /opt/openfoam8

stages:
  - build
  - run

addons:
  apt:
    update: true
    packages:
      - flexc++
      - libfl-dev
      - lcov
      - libopenmpi-dev

script: skip

_build: &_build
  stage: build
  before_install:
    - sudo sh -c "wget --no-check-certificate -O - https://dl.openfoam.org/gpg.key | apt-key add -"
    - sudo add-apt-repository http://dl.openfoam.org/ubuntu
    - sudo apt update
    - sudo apt-get -y install openfoam$VERSION
    - source /opt/openfoam$VERSION/etc/bashrc

  install:
    - ./scripts/travis_install_external_ginkgo.sh

  before_script:
    - cmake --version
    - mkdir build
    - cd build
    - cmake -DOGL_USE_EXTERNAL_GINKGO=$EXTERNAL_GINKGO ..

  script:
    - make -j4 && make install


_run: &_run
  stage: run
  before_install:
    - sudo sh -c "wget --no-check-certificate -O - https://dl.openfoam.org/gpg.key | apt-key add -"
    - sudo add-apt-repository http://dl.openfoam.org/ubuntu
    - sudo apt update
    - sudo apt-get -y install openfoam$VERSION
    - source /opt/openfoam$VERSION/etc/bashrc

  install:
    - git clone https://github.com/greole/OBR.git $HOME/OBR
    - pip install docopt --user


  script:
      - ls /opt
      - ls $FOAM_SRC
      - ls $FOAM_USER_LIBBIN
      - cd $HOME/OBR
      - python runBenchmark.py \
          --solver CG,BiCGStab \
          --backend OF,GKO     \
          --executor Ref       \
          --preconditioner NoPrecond \
          --field p,U          \
          --small-cases        \
          --test-run           \
          --fail_on_error      \
          --report=report.csv  \
          --folder=Test        \
          --project_path /home/travis/cache/OBR

jobs:
  include:
    - <<: *_build
      ENV:
      - VERSION=8
      - EXTERNAL_GINKGO=OFF
      - GINKGO_VERSION=develop
      workspaces:
        create:
          name:
            foam_user_libbin_8
          paths:
            /home/travis/OpenFOAM/travis-8
    - <<: *_build
      ENV:
      - VERSION=8
      - EXTERNAL_GINKGO=ON
      - GINKGO_VERSION=develop
    - <<: *_build
      ENV:
      - VERSION=8
      - EXTERNAL_GINKGO=ON
      - GINKGO_VERSION=331277a81b848f33705f6ccf4f910fff69c84e18
    - <<: *_build
      ENV:
      - VERSION=7
      - EXTERNAL_GINKGO=OFF
      - GINKGO_VERSION=develop
      workspaces:
        create:
          name:
            foam_user_libbin_7
          paths:
            /home/travis/OpenFOAM/travis-7
    - <<: *_build
      ENV:
      - VERSION=7
      - EXTERNAL_GINKGO=ON
      - GINKGO_VERSION=develop
    - <<: *_run
      ENV:
      - VERSION=8
      workspaces:
        use: foam_user_libbin_8
